backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "static/img"

collections:
  - label: "SCDTSEA News"
    name: "news"
    folder: "news"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Summary", name: "summary", widget: "text"}
      - {label: "Read More", name: "read_more", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", default: ["post"]}
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Us"
        name: "about"
        file: "pages/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Complete SCDTSEA History"
        name: "complete_history"
        file: "pages/complete_history.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "History", name: "history", widget: "markdown"}
      - label: "Past SCDTSEA Presidents"
        name: "past_presidents"
        file: "pages/past_presidents.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - label: "Past Presidents"
            name: "past_presidents"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Location/Organization", name: "location_organization", widget: "string"}
              - {label: "Years", name: "years", widget: "string"}
      - label: "SCDTSEA Constitution"
        name: "constitution"
        file: "pages/constitution.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Privacy Policy"
        name: "privacy_policy"
        file: "pages/privacy_policy.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Useful Links"
        name: "useful_links"
        file: "pages/useful_links.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Links", name: "links", widget: "markdown"}
      - label: "Board Members"
        name: "board_members"
        file: "pages/board_members.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - label: "Board Members"
            name: "board_members"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Position", name: "position", widget: "string"}
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Bio", name: "bio", widget: "markdown"}
              - {label: "Active", name: "active", widget: "boolean", default: true}
      - label: "Awards"
        name: "awards"
        file: "pages/awards.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Opening Paragraph", name: "opening_paragraph", widget: "markdown"}
          - label: "Awards"
            name: "awards"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Criteria", name: "criteria", widget: "markdown"}
      - label: "Poster Contest Award Recipients"
        name: "poster_contest_recipients"
        file: "pages/award_recipients/poster_contest.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - label: "Recipients"
            name: "recipients"
            widget: "list"
            fields:
              - {label: "Year", name: "year", widget: "string"}
              - {label: "Recipient ", name: "recipient", widget: "markdown"}
      


#    folder: "pages"
    #create: false # Change to true to allow editors to create new pages
    #slug: "{{slug}}"
    #fields:
      #- { label: "Title", name: "title", widget: "string" }
      #- { label: "Publish Date", name: "date", widget: "datetime" }
      #- { label: "Permalink", name: "permalink", widget: "string" }
      #- label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        #name: "eleventyNavigation"
        #widget: "object"
        #fields:
          #- { label: "Key", name: "key", widget: "string" }
          #- { label: "Order", name: "order", widget: "number", default: 0 }
      #- { label: "Body", name: "body", widget: "markdown" }
  # Authors
  - name: "authors"
    label: "Author"
    folder: "authors"
    create: true
    slug: "{{fields.name}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "GitHub", name: "github", widget: "string"}
