backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "static/img"

collections:
  - label: "SCDTSEA News"
    name: "news"
    folder: "news"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Summary", name: "summary", widget: "text"}
      - {label: "Read More", name: "read_more", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", default: ["post"]}
  - label: "Board Members"
    name: "board"
    folder: "board_members"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Bio", name: "bio", widget: "markdown"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "pages/home.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "About Us"
        name: "about"
        file: "pages/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "A Brief History of SCDTSEA"
        name: "history"
        file: "pages/history.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "History", name: "history", widget: "markdown"}
      - label: "Past SCDTSEA Presidents"
        name: "past_presidents"
        file: "pages/past_presidents.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - label: "Past Presidents"
            name: "past_presidents"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Location/Organization", name: "location_organization", widget: "string"}
              - {label: "Years", name: "years", widget: "string"}
      - label: "SCDTSEA Constitution"
        name: "constitution"
        file: "pages/constitution.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Privacy Policy"
        name: "privacy_policy"
        file: "pages/privacy_policy.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Useful Links"
        name: "useful_links"
        file: "pages/useful_links.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Links", name: "links", widget: "markdown"}
      - label: "Become a Member"
        name: "become_member"
        file: "pages/become_member.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Board Members"
        name: "board_members"
        file: "pages/board_members.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - label: "Board Members"
            name: "board_members"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Position", name: "position", widget: "string"}
      - label: "Awards"
        name: "awards"
        file: "pages/awards.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - label: "Awards"
            name: "awards"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
      - label: "Poster Contest Award Recipients"
        name: "poster_contest_recipients"
        file: "pages/award/poster_contest.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - label: "Recipients"
            name: "recipients"
            widget: "list"
            fields:
              - {label: "Year", name: "year", widget: "string"}
              - {label: "Recipient ", name: "recipient", widget: "markdown"}
