backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo under images/uploads

collections:
  - label: "Post" # Used in the UI
    name: "blog" # Used in routes, e.g., /admin/collections/blog
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "Post Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        searchFields: ["name", "github"]
        valueField: "name"
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }
  # Our pages e.g. About
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Us"
        name: "about"
        file: "pages/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Establishment", name: "establishment", widget: "markdown"}
          - {label: "Our Mission Statement", name: "mission_statement", widget: "markdown"}
          - {label: "Purpose", name: "purpose", widget: "markdown"}
          - {label: "Types of Members", name: "types_of_members", widget: "markdown"}
          - {label: "Board Members", name: "board_members", widget: "markdown"}
      - label: "Complete SCDTSEA History"
        name: "complete_history"
        file: "pages/complete_history.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "History", name: "history", widget: "markdown"}


#    folder: "pages"
    #create: false # Change to true to allow editors to create new pages
    #slug: "{{slug}}"
    #fields:
      #- { label: "Title", name: "title", widget: "string" }
      #- { label: "Publish Date", name: "date", widget: "datetime" }
      #- { label: "Permalink", name: "permalink", widget: "string" }
      #- label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        #name: "eleventyNavigation"
        #widget: "object"
        #fields:
          #- { label: "Key", name: "key", widget: "string" }
          #- { label: "Order", name: "order", widget: "number", default: 0 }
      #- { label: "Body", name: "body", widget: "markdown" }
  # Authors
  - name: "authors"
    label: "Author"
    folder: "authors"
    create: true
    slug: "{{fields.name}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "GitHub", name: "github", widget: "string"}
